#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
realtime_like_backtest_updated1.py – Live‑style back‑test **with snapshot**
────────────────────────────────────────────────────────────────────────────
This script emulates the exact online inference loop.
It now *always* dumps a snapshot of the *final* feature‑matrix so that it can
be compared to the chimney snapshot generated by
``chimney_test_thr_updated.py``.

Headline changes (2025‑07‑09)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* **New ``--snapshot`` flag** (default ``live_snapshot.csv``).
* **New ``--compare-with`` flag** to immediately run
  ``compare_feature_sets.py`` after the back‑test finishes.
* Snapshot is written **both** in ``--whole-pass`` *and* incremental mode.
  In incremental mode we accumulate each step's feature‑vector in a list and
  concatenate at the end.
* Casts every feature to ``float32`` to match chimney.
"""
from __future__ import annotations

import argparse
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score

from prepare_data_for_train import PREPARE_DATA_FOR_TRAIN
from dynamic_threshold_adjuster import DynamicThresholdAdjuster

###############################################################################
# Configuration / helpers
###############################################################################
RAW_FILES: Dict[str, str] = {
    "30T": "XAUUSD_M30.csv",
    "15T": "XAUUSD_M15.csv",
    "5T" : "XAUUSD_M5.csv",
    "1H" : "XAUUSD_H1.csv",
}

MAX_ROWS = 10_000
LOGFILE = "realtime_like_backtest.log"
DEFAULT_SNAPSHOT = "live_snapshot.csv"

def _load_csv(path: Path) -> pd.DataFrame:
    if not path.is_file():
        raise FileNotFoundError(path)
    df = pd.read_csv(path, parse_dates=["time"], low_memory=False)
    df.sort_values("time", inplace=True, ignore_index=True)
    return df

###############################################################################
# CLI
###############################################################################

cli = argparse.ArgumentParser("Realtime‑like back‑test (30‑minute cadence)")
cli.add_argument("--start", default="2024-01-02 00:00",
                 help="ISO start datetime (e.g. 2024-01-02 00:00)")
cli.add_argument("--rows", type=int, default=2000,
                 help="exact rows to keep for snapshot (default 2 000)")
cli.add_argument("--whole-pass", action="store_true",
                 help="run WHOLE‑PASS mode (single batch) like chimney")
cli.add_argument("--model", default="best_model.pkl")
cli.add_argument("--snapshot", default=DEFAULT_SNAPSHOT,
                 help="CSV path to dump feature snapshot")
cli.add_argument("--compare-with", metavar="CHIMNEY_SNAPSHOT",
                 help="if given, run compare_feature_sets.py")
cli.add_argument("--dyn-thr", action="store_true",
                 help="enable DynamicThresholdAdjuster at inference time")
cli.add_argument("--verbose", action="store_true")
args = cli.parse_args()

###############################################################################
# Logging
###############################################################################

console_lvl = logging.DEBUG if args.verbose else logging.INFO
logging.basicConfig(
    level=logging.INFO,
    handlers=[
        logging.FileHandler(LOGFILE, "w", encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("rt‑backtest")
log.setLevel(console_lvl)

###############################################################################
# Load raw CSVs
###############################################################################

raw_df = {tf: _load_csv(Path(fn)) for tf, fn in RAW_FILES.items()}
for tf, df in raw_df.items():
    raw_df[tf] = (
        df.loc[~df["time"].dt.dayofweek.isin([5, 6])]  # remove weekends
          .drop_duplicates(subset="time", keep="last")
          .reset_index(drop=True)
    )
log.info("✅ Loaded %d CSVs | rows (30T)=%d", len(raw_df), len(raw_df["30T"]))

###############################################################################
# Load model & META
###############################################################################

mdl_path = Path(args.model).resolve()
if not mdl_path.is_file():
    log.error("Model not found: %s", mdl_path)
    sys.exit(1)
mdl = joblib.load(mdl_path)
pipe = mdl["pipeline"]
neg_thr, pos_thr = mdl["neg_thr"], mdl["pos_thr"]
window, feats, all_cols = mdl["window_size"], mdl["feats"], mdl["train_window_cols"]
log.info("Model meta | window=%d | thr=(%.3f, %.3f)", window, neg_thr, pos_thr)

###############################################################################
# PREP instance
###############################################################################

prep = PREPARE_DATA_FOR_TRAIN(filepaths=RAW_FILES, main_timeframe="30T", verbose=False)
time_col = f"{prep.main_timeframe}_time"

###############################################################################
# WHOLE‑PASS MODE   (single batch – matches chimney exactly)
###############################################################################

if args.whole_pass:
    log.info("⚡ WHOLE‑PASS mode … building complete feature‑matrix")
    merged = prep.load_data()
    X_all, y_all, _ = prep.ready(merged, window=window, selected_features=feats, mode="train")
    ts_all = merged[time_col].iloc[window : window + len(X_all)].reset_index(drop=True)

    # Apply --start / --rows filters
    start_ts = pd.Timestamp(args.start)
    keep = ts_all >= start_ts
    X_all, y_all, ts_all = X_all[keep], y_all[keep], ts_all[keep]
    if args.rows and len(X_all) > args.rows:
        X_all, y_all, ts_all = (
            df.tail(args.rows).reset_index(drop=True) for df in (X_all, y_all, ts_all)
        )

    X_eval = X_all.reindex(columns=all_cols).astype("float32")

    # Snapshot
    snap_path = Path(args.snapshot).resolve()
    X_eval.assign(**{time_col: ts_all.dt.strftime("%Y-%m-%d %H:%M:%S")}).to_csv(snap_path, index=False)
    log.info("📄 Snapshot saved (%d rows) → %s", len(X_eval), snap_path)

    # Metrics
    proba = pipe.predict_proba(X_eval)[:, 1]
    y_pred = np.full_like(y_all.values, -1)
    y_pred[proba <= neg_thr] = 0
    y_pred[proba >= pos_thr] = 1
    mask = y_pred != -1
    acc = accuracy_score(y_all[mask], y_pred[mask]) if mask.any() else 0.0
    f1 = f1_score(y_all[mask], y_pred[mask]) if mask.any() else 0.0
    log.info("WHOLE‑PASS | rows=%d | decided=%d | Acc=%.4f | F1=%.4f",
             len(X_eval), mask.sum(), acc, f1)
else:
    ############################################################################
    # INCREMENTAL MODE  (30‑minute cadence loop)
    ############################################################################
    log.info("🔄 Incremental mode … this may take a while")

    merged_all = prep.load_data()
    start_ts = pd.Timestamp(args.start)
    merged_all = merged_all[merged_all[time_col] >= start_ts].reset_index(drop=True)

    # Container for snapshots
    snap_rows: List[pd.Series] = []
    y_true_all: List[int] = []
    y_pred_all: List[int] = []

    dta = DynamicThresholdAdjuster() if args.dyn_thr else None

    # Classic sliding window over merged_all (simulate live feed)
    for idx in range(window, len(merged_all)):
        sub = merged_all.iloc[idx - window : idx + 1].copy().reset_index(drop=True)
        X_inc, _ = prep.ready_incremental(sub, window=window, selected_features=feats)
        ts = merged_all.loc[idx, time_col]

        # Align columns, cast
        for col in all_cols:
            if col not in X_inc.columns:
                X_inc[col] = np.nan
        X_inc = X_inc[all_cols].astype("float32")

        # Proba → prediction
        proba = float(pipe.predict_proba(X_inc)[:, 1])
        n_thr, p_thr = (dta.adjust(neg_thr, pos_thr, last_atr=sub[f"30T_atr_14"].iloc[-1],
                                   last_volume=sub[f"30T_volume"].iloc[-1])
                        if dta else (neg_thr, pos_thr))
        pred = -1
        if proba <= n_thr:
            pred = 0
        elif proba >= p_thr:
            pred = 1

        # Append snapshot row (only if we will include in final CSV)
        snap_rows.append(pd.Series({**{time_col: ts}, **{c: X_inc.iloc[0][c] for c in all_cols}}))
        y_true_all.append(int(((sub[f"30T_close"].iloc[-1] - sub[f"30T_close"].iloc[-2]) > 0)))
        y_pred_all.append(pred)

    # Build snapshot DF ↘
    snap_df = pd.DataFrame(snap_rows)
    if args.rows and len(snap_df) > args.rows:
        snap_df = snap_df.tail(args.rows).reset_index(drop=True)

    snap_path = Path(args.snapshot).resolve()
    snap_df.to_csv(snap_path, index=False)
    log.info("📄 Snapshot saved (%d rows) → %s", len(snap_df), snap_path)

    # Metrics
    y_true_np = np.array(y_true_all[-len(snap_df):])
    y_pred_np = np.array(y_pred_all[-len(snap_df):])
    mask = y_pred_np != -1
    acc = accuracy_score(y_true_np[mask], y_pred_np[mask]) if mask.any() else 0.0
    f1 = f1_score(y_true_np[mask], y_pred_np[mask]) if mask.any() else 0.0
    log.info("INCREMENTAL | rows=%d | decided=%d | Acc=%.4f | F1=%.4f",
             len(snap_df), int(mask.sum()), acc, f1)

###############################################################################
# Optional automatic diff
###############################################################################

if args.compare_with:
    ref_path = Path(args.compare_with).resolve()
    if not ref_path.is_file():
        log.error("--compare-with file not found: %s", ref_path)
    else:
        log.info("🔍 Running feature diff vs. chimney snapshot …")
        try:
            subprocess.run([
                sys.executable,
                "compare_feature_sets.py",
                "--ref", str(ref_path),
                "--live", str(snap_path),
                "--time-col", time_col,
            ], check=True)
        except subprocess.CalledProcessError as exc:
            log.error("Diff tool exited with code %d", exc.returncode)

print(f"Live snapshot : {snap_path}\nChimney diff   : {ref_path if args.compare_with else '—'}")
